FROM python:2.7-alpine

WORKDIR /usr/src/app
COPY source/jormungandr/requirements.txt /usr/src/app
COPY source/jormungandr/jormungandr /usr/src/app/jormungandr
COPY source/navitiacommon/navitiacommon /usr/src/app/navitiacommon

RUN apk --update add \
        g++ \
        build-base \
        python-dev \
        zlib-dev \
        linux-headers \
        musl \
        musl-dev \
        git \
        postgresql-dev && \
    pip install -U pip && \
    pip install uwsgi && \
    pip install --no-cache-dir -r requirements.txt && \
    apk del \
        g++ \
        build-base \
        python-dev \
        zlib-dev \
        linux-headers \
        musl \
        musl-dev \
        postgresql-dev && \
    rm -rf /var/apk/cache/*

EXPOSE 5000

